import {spawn,execFileSync} from 'node:child_process';
import {mkdir,mkdtemp,cp,readFile,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {createServer} from 'node:http';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/client';
import {StdioClientTransport} from '@modelcontextprotocol/client/stdio';

const base=path.resolve('.test-state');await mkdir(base,{recursive:true});const directory=await mkdtemp(path.join(base,'capabilities-'));
const judge=path.join(directory,'judge'),state=path.join(directory,'state'),extension=path.join(directory,'extension'),python=process.env.TABORA_BENCH_PYTHON??'python',world=path.resolve('../browser-capability-bench/world.py');
const child=spawn(python,[world,'serve','--judge-dir',judge,'--seed','11'],{windowsHide:true,stdio:['ignore','pipe','pipe']});child.stderr.on('data',data=>process.stderr.write(data));
const origin=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(new Error('World startup timeout')),15000);child.once('error',reject);child.stdout.on('data',data=>{output+=data;const index=output.indexOf('\n');if(index>=0){clearTimeout(timer);resolve(JSON.parse(output.slice(0,index)).public_url);}});});
await cp('dist/extension',extension,{recursive:true});const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions=['http://127.0.0.1/*'];await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));
const extensionId=(await readFile('extension-id.txt','utf8')).trim(),checks=[],sensorPairs=[];let context,client;
const watchdog=setTimeout(()=>{console.error('Capability integration timed out');process.exit(1);},180000);
const readinessServer=createServer((request,response)=>{
  if(request.url==='/probe'){response.writeHead(200,{'content-type':'text/html'});response.end('<!doctype html><head><script defer src="/script"></script></head><body><button id="ready">Ready</button><div id="shadow-one"></div><div id="shadow-two"></div><img src="/image">');}
  else if(request.url==='/script')setTimeout(()=>{response.writeHead(200,{'content-type':'text/javascript'});response.end('document.querySelector("#ready").dataset.initialized="yes";document.querySelector("#shadow-one").attachShadow({mode:"closed"}).innerHTML="<p>First private-root paragraph</p>";document.querySelector("#shadow-two").attachShadow({mode:"open"}).innerHTML="<p>Second root paragraph</p>";');},600);
  else if(request.url==='/image'){response.writeHead(200,{'content-type':'image/png'});response.flushHeaders();}
  else {response.writeHead(404);response.end();}
});
await new Promise(resolve=>readinessServer.listen(0,'127.0.0.1',resolve));const readinessOrigin='http://127.0.0.1:'+readinessServer.address().port;
async function tool(name,args={},expected){const reply=await client.callTool({name,arguments:args}),data=JSON.parse(reply.content.find(c=>c.type==='text').text);if(expected){assert(reply.isError,JSON.stringify(data));assert.equal(data.code,expected);}else assert(!reply.isError,JSON.stringify(data));return data;}
async function observe(task){return tool('browser_state',{sessionId:task.sessionId});}
async function act(task,observation,action){const plan=await tool('browser_plan',{sessionId:task.sessionId,stateVersion:observation.stateVersion,action});return tool('browser_commit',{sessionId:task.sessionId,actionId:plan.actionId,stateVersion:plan.stateVersion});}
function target(observation,name,kind){const matches=observation.snapshot.targets.filter(t=>t.name===name&&(!kind||t.kind===kind));assert.equal(matches.length,1,JSON.stringify(matches));return matches[0];}
async function saved(task){await task.page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved'));const result=JSON.parse(execFileSync(python,[world,'grade','--judge-dir',judge,'--case',task.caseId],{windowsHide:true,encoding:'utf8'}));assert(result.cases[0].outcome_passed,JSON.stringify(result));}
try{
  context=await chromium.launchPersistentContext(path.join(directory,'chromium'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`],env:{...process.env,TABORA_STATE_DIR:state}});
  // The extension owns dialog handling. Playwright's implicit auto-dismiss would be a competing executor.
  context.on('dialog',()=>{});
  const panel=await context.newPage();await panel.goto(`chrome-extension://${extensionId}/panel.html`);await panel.waitForFunction(()=>document.querySelector('#connection')?.textContent==='Lokální host připojený');
  const profileId=(await panel.evaluate(()=>chrome.runtime.sendMessage({command:'status'}))).data.profile.id;await panel.close();
  client=new Client({name:'capability-integration',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:[path.resolve('dist/host/mcp.js')],env:{...process.env,TABORA_STATE_DIR:state},stderr:'pipe'}));
  const readySession=await tool('browser_session_create',{profileId,name:'DOM readiness and shadow provenance',allowedOrigins:[readinessOrigin]}),readyStarted=performance.now();
  const readyOpen=await tool('browser_session_open',{sessionId:readySession.id,url:readinessOrigin+'/probe',waitForReady:true,readinessTimeoutMs:4000});assert(readyOpen.attached,JSON.stringify(readyOpen));
  const readyPage=context.pages().find(page=>page.url()===readinessOrigin+'/probe');
  assert.equal(await readyPage.evaluate(()=>document.querySelector('#ready').dataset.initialized),'yes','Binding must wait for deferred initialization');
  assert(performance.now()-readyStarted<4000,'An unfinished image must not hold DOM readiness hostage');assert.equal(await readyPage.evaluate(()=>document.readyState),'interactive');
  const rooted=await tool('browser_state',{sessionId:readySession.id}),paragraphs=rooted.snapshot.targets.filter(target=>target.kind==='paragraph');assert.equal(paragraphs.length,2);assert.deepEqual(paragraphs.map(target=>target.shadowRootPath),[[1],[2]]);
  for(const [index,paragraph] of paragraphs.entries()){const read=await tool('browser_read',{sessionId:readySession.id,targetId:paragraph.id,format:'text'});assert.equal(read.text.trim(),index?'Second root paragraph':'First private-root paragraph');}
  await tool('browser_session_release',{sessionId:readySession.id,closeCreatedTabs:true});checks.push('parsed document waits for deferred initialization, not unfinished images; exact paragraphs retain open/closed shadow-root provenance');
  async function task(family,variant=1,options={}){const caseId=`BCB-${family}-V${String(variant).padStart(2,'0')}`,s=await tool('browser_session_create',{profileId,name:caseId,...options}),url=`${origin}/task/${caseId}`,opened=await tool('browser_session_open',{sessionId:s.id,url,active:true,waitForReady:true});assert(opened.attached,JSON.stringify(opened));return {caseId,sessionId:s.id,tabId:opened.tabId,page:context.pages().filter(p=>p.url()===url).at(-1)};}
  const c1=await task('C01'),one=await observe(c1);assert(target(one,'Save customer','button'));
  const cdp=await context.newCDPSession(c1.page),ax=await cdp.send('Accessibility.getFullAXTree');assert(ax.nodes.some(n=>n.role?.value==='button'&&n.name?.value==='Save customer'));await cdp.detach();
  await act(c1,one,{type:'click',targetId:target(one,'Save customer','button').id});await saved(c1);checks.push('accessible name agrees with independent Chrome AX');
  const c2=await task('C02'),two=await observe(c2),tasks=await (await fetch(origin+'/tasks')).json(),value=tasks.find(t=>t.id===c2.caseId).goal.match(/^Enter (.*?) into/)[1];
  let observed=await act(c2,two,{type:'fill',targetId:target(two,'Customer','textbox').id,value});assert.equal(target(observed,'Customer','textbox').value,value);
  await act(c2,observed,{type:'click',targetId:target(observed,'Save','button').id});await saved(c2);checks.push('standalone field updates DOM and actual server record');
  const c3=await task('C03'),three=await observe(c3);observed=await act(c3,three,{type:'check',targetId:target(three,'Accept terms','checkbox').id,checked:true});
  const repeated=await act(c3,observed,{type:'check',targetId:target(observed,'Accept terms','checkbox').id,checked:true});assert.equal(repeated.action.dispatch,'not_needed');
  await act(c3,repeated,{type:'click',targetId:target(repeated,'Save','button').id});await saved(c3);checks.push('checkbox desired state is idempotent and server verified');
  for(const completed of [c1,c2,c3])await tool('browser_session_release',{sessionId:completed.sessionId});
  for(const family of ['C04','C07','C15']){const t=await task(family),o=await observe(t);await act(t,o,{type:'click',targetId:target(o,'Save','button').id});await saved(t);checks.push(family+' fixed DOM execution');}
  const trusted=await task('C06'),trustedState=await observe(trusted);await act(trusted,trustedState,{type:'click',targetId:target(trustedState,'Save','button').id,backend:'native'});await saved(trusted);checks.push('native mouse isTrusted updates independent server');
  const hoverTask=await task('C06',2),hoverState=await observe(hoverTask);let hoverResult=await act(hoverTask,hoverState,{type:'hover',targetId:target(hoverState,'Actions','button').id});await act(hoverTask,hoverResult,{type:'click',targetId:target(hoverResult,'Save','button').id});await saved(hoverTask);await tool('browser_session_release',{sessionId:hoverTask.sessionId});checks.push('trusted hover reveals an executable menu');
  const keyTask=await task('C06',3),keyState=await observe(keyTask);await act(keyTask,keyState,{type:'key',targetId:target(keyState,'Save','button').id,key:'Enter'});await saved(keyTask);await tool('browser_session_release',{sessionId:keyTask.sessionId});checks.push('trusted keyboard input follows exact focus binding');
  const focusTask=await task('C06',3);await focusTask.page.evaluate(()=>{const input=document.createElement('input');input.setAttribute('aria-label','Unrelated editor');document.body.append(input);});
  const focusState=await observe(focusTask),focusWorker=context.serviceWorkers().find(worker=>worker.url().startsWith('chrome-extension://'));
  const sensorCall=async payload=>(await focusWorker.evaluate(async({tabId,documentId,payload})=>{const results=await chrome.scripting.executeScript({target:{tabId,documentIds:[documentId]},world:'ISOLATED',func:input=>globalThis.__taboraOperation(input),args:[payload]});return results[0].result;},{tabId:focusTask.tabId,documentId:focusState.binding.documentId,payload:{origin,...payload,sessionId:focusTask.sessionId,documentToken:focusState.snapshot.provenance.documentToken}}));
  const focusLease=await sensorCall({op:'native_prepare',snapshotId:focusState.snapshot.snapshotId,action:{type:'key',targetId:target(focusState,'Save','button').id,key:'Enter'}});assert(focusLease.ok);
  await focusTask.page.getByRole('textbox',{name:'Unrelated editor'}).focus();const focusDenied=await sensorCall({op:'native_validate',leaseId:focusLease.leaseId});assert.equal(focusDenied.code,'focus_lost');
  assert.equal(await focusTask.page.getByRole('textbox',{name:'Unrelated editor'}).inputValue(),'');await tool('browser_session_release',{sessionId:focusTask.sessionId});checks.push('element focus drift rejects native key lease before dispatch');
  const dragTask=await task('C08',3),dragState=await observe(dragTask),drag=await act(dragTask,dragState,{type:'drag',targetId:target(dragState,'Record A','listitem').id,destinationId:target(dragState,'Destination','region').id});assert.equal(drag.action.dispatch,'sent',JSON.stringify(drag));await saved(dragTask);await tool('browser_session_release',{sessionId:dragTask.sessionId});checks.push('trusted HTML drag/drop reaches the independent server');
  const canvasTask=await task('C17',4),canvasState=await observe(canvasTask),canvas=target(canvasState,'Action chart','img'),canvasCapture=await tool('browser_capture',{sessionId:canvasTask.sessionId,targetId:canvas.id,stateVersion:canvasState.stateVersion});
  const preview=await client.callTool({name:'browser_image_view',arguments:{sessionId:canvasTask.sessionId,artifactId:canvasCapture.artifact.id}});assert(!preview.isError);assert(preview.content.some(content=>content.type==='image'&&content.mimeType==='image/jpeg'&&content.data.length<=160000));
  await tool('browser_plan',{sessionId:canvasTask.sessionId,stateVersion:canvasState.stateVersion,action:{type:'image_click',targetId:canvas.id,captureId:canvasCapture.visual.captureId,x:4096,y:80}},'stale_capture');
  await act(canvasTask,canvasState,{type:'image_click',targetId:canvas.id,captureId:canvasCapture.visual.captureId,x:190,y:80});await saved(canvasTask);await tool('browser_session_release',{sessionId:canvasTask.sessionId});checks.push('explicit MCP image preview and capture-bound canvas click');
  const c9=await task('C09'),nine=await observe(c9),pre=nine.snapshot.targets.find(t=>t.kind==='generic'&&t.name.startsWith('xxxx'));assert(pre);
  const chunk1=await tool('browser_read',{sessionId:c9.sessionId,targetId:pre.id,limit:8000});assert(chunk1.nextOffset);
  const chunk2=await tool('browser_read',{sessionId:c9.sessionId,targetId:pre.id,offset:16000,limit:8000,revision:chunk1.revision});assert(chunk2.text.includes('00012345678901234567890'));checks.push('exact reader beyond legacy limits preserves long identifiers');
  const c12=await task('C12'),twelve=await observe(c12),select=target(twelve,'Record','combobox');assert.equal(select.optionCount,80);
  const options=await tool('browser_read',{sessionId:c12.sessionId,targetId:select.id,format:'options',offset:40,limit:40});assert.equal(options.options[39].label,'Record 79');
  observed=await act(c12,twelve,{type:'select',targetId:select.id,indices:[79]});assert.equal(await c12.page.locator('#choices').evaluate(el=>el.selectedIndex),79);checks.push('option continuation and selection outside first 40');
  const baseline=await observe(c12);await c12.page.evaluate(()=>document.querySelector('#choices').disabled=true);const delta=await tool('browser_state',{sessionId:c12.sessionId,baseSnapshotId:baseline.snapshot.snapshotId});assert.equal(delta.fullSnapshot,false);assert(delta.snapshot.changed.some(t=>t.id===select.id&&t.disabled));checks.push('stable refs and property-state delta');
  const full=await tool('browser_state',{sessionId:c12.sessionId,baseSnapshotId:crypto.randomUUID()});assert(full.fullSnapshot);checks.push('missing delta baseline restores full observation');
  for(let pair=0;pair<12;pair++){
    const first=await tool('browser_state',{sessionId:c12.sessionId,fresh:true}),second=await tool('browser_state',{sessionId:c12.sessionId});assert.deepEqual(second.snapshot.targets,first.snapshot.targets);sensorPairs.push({freshMs:first.timings.sensorMs,cachedMs:second.timings.sensorMs,treeCacheHit:second.timings.treeCacheHit,semanticHits:second.timings.semanticHits});
  }checks.push('paired fresh/cached observations preserve identical semantic state');
  const tableTask=await task('C10'),tableState=await observe(tableTask),table=tableState.snapshot.targets.find(t=>t.kind==='table');assert(table);
  const aggregate=await tool('browser_read',{sessionId:tableTask.sessionId,targetId:table.id,format:'aggregate',column:1,operation:'sum',decimal:',',group:' '});assert.equal(aggregate.aggregate.value,'3580.10');checks.push('exact locale-aware table sum');
  const spanTask=await task('C10',2),spanState=await observe(spanTask),spanTable=spanState.snapshot.targets.find(target=>target.kind==='table'),spanRead=await tool('browser_read',{sessionId:spanTask.sessionId,targetId:spanTable.id,format:'rows'});assert.deepEqual(spanRead.headers,['Name','Totals / Amount','Totals / Tax']);assert.equal(spanRead.rows[2][0],'000123');
  const spanSum=await tool('browser_read',{sessionId:spanTask.sessionId,targetId:spanTable.id,format:'aggregate',column:1,operation:'sum',decimal:',',group:' '});assert.equal(spanSum.aggregate.value,'3580.10');await tool('browser_session_release',{sessionId:spanTask.sessionId});checks.push('real rowspan/colspan headers preserve identifiers and exact aggregates');
  const paged=await task('C02',2);await paged.page.evaluate(()=>{const main=document.querySelector('main');for(let index=0;index<125;index++){const button=document.createElement('button');button.textContent='Action '+index;main.prepend(button);}});
  const firstPage=await tool('browser_state',{sessionId:paged.sessionId,limit:10}),earlier=firstPage.snapshot.targets.find(target=>target.kind==='button');assert(earlier);let nextPage=await tool('browser_state',{sessionId:paged.sessionId,cursor:firstPage.snapshot.coverage.nextCursor,limit:10});assert.equal(nextPage.continuationOf,firstPage.snapshot.snapshotId);
  await act(paged,nextPage,{type:'click',targetId:earlier.id});const newer=await tool('browser_state',{sessionId:paged.sessionId,limit:10});await paged.page.evaluate(()=>{document.querySelector('main').append(document.createElement('button'));});await tool('browser_state',{sessionId:paged.sessionId,cursor:newer.snapshot.coverage.nextCursor,limit:10},'stale_continuation');await tool('browser_session_release',{sessionId:paged.sessionId});checks.push('observation continuation retains earlier refs and rejects a changed target sequence');
  const chartTask=await task('C17'),chartState=await observe(chartTask),chart=target(chartState,'Quarterly chart','img');
  const capture=await tool('browser_capture',{sessionId:chartTask.sessionId,targetId:chart.id,stateVersion:chartState.stateVersion});assert.equal(capture.exportedToProvider,false);
  const ocr=await tool('browser_document_read',{sessionId:chartTask.sessionId,artifactId:capture.artifact.id,format:'ocr'});assert(ocr.text.includes('120')&&ocr.text.includes('140'),JSON.stringify(ocr));assert.equal(ocr.provenance.localOnly,true);checks.push('owned-region capture and offline OCR');
  const downloadTask=await task('C18'),downloadState=await observe(downloadTask),download=await tool('browser_download',{sessionId:downloadTask.sessionId,targetId:target(downloadState,'Download invoice','link').id,stateVersion:downloadState.stateVersion,name:'invoice.pdf'});
  const pdf=await tool('browser_document_read',{sessionId:downloadTask.sessionId,artifactId:download.artifact.id,format:'pdf',layout:true});assert(pdf.text.includes('00012345678901234567890')&&pdf.text.includes('1234.50'),JSON.stringify(pdf));assert.equal(pdf.precision,'pdf_text');assert(pdf.layout.items.length>0);checks.push('task-owned browser download and actual PDF text/glyph layout extraction');
  await tool('browser_document_read',{sessionId:chartTask.sessionId,artifactId:download.artifact.id,format:'pdf'},'file_not_owned');checks.push('cross-session document access denied');
  const editorTask=await task('C08'),editorState=await observe(editorTask),editorValue=tasks.find(t=>t.id===editorTask.caseId).goal.match(/^Enter (.*?) into/)[1];
  observed=await act(editorTask,editorState,{type:'replace',targetId:target(editorState,'Customer','textbox').id,start:0,end:8,text:editorValue});await act(editorTask,observed,{type:'click',targetId:target(observed,'Save','button').id});await saved(editorTask);checks.push('editor replacement updates website record');
  const gridTask=await task('C11'),gridState=await observe(gridTask),grid=target(gridState,'Customers','grid');await tool('browser_read',{sessionId:gridTask.sessionId,targetId:grid.id,format:'aggregate',column:0,operation:'count',decimal:'.',group:''},'incomplete_dataset');
  const gridPlan=await tool('browser_plan',{sessionId:gridTask.sessionId,stateVersion:gridState.stateVersion,action:{type:'click',targetId:target(gridState,'Save','button').id}});
  await gridTask.page.evaluate(()=>document.querySelector('[role="row"]').setAttribute('data-key','customer-two'));await tool('browser_commit',{sessionId:gridTask.sessionId,actionId:gridPlan.actionId,stateVersion:gridPlan.stateVersion},'stale_reference');checks.push('recycled record rejected and virtual aggregate never claims complete');
  const frameTask=await task('C14'),frames=await tool('browser_frames',{sessionId:frameTask.sessionId}),frame=frames.frames.find(f=>f.frameId!==0);assert(frame.allowed);const frameState=await tool('browser_state',{sessionId:frameTask.sessionId,frameId:frame.frameId});
  const framePlan=await tool('browser_plan',{sessionId:frameTask.sessionId,frameId:frame.frameId,stateVersion:frameState.stateVersion,action:{type:'click',targetId:target(frameState,'Save','button').id,backend:'native'}});
  const frameAction=await tool('browser_commit',{sessionId:frameTask.sessionId,actionId:framePlan.actionId,stateVersion:framePlan.stateVersion});assert.equal(frameAction.action.dispatch,'sent',JSON.stringify(frameAction));await frameTask.page.frames()[1].waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved'));checks.push('native input maps permitted iframe coordinates');
  const deniedTask=await task('C14',3),deniedFrames=await tool('browser_frames',{sessionId:deniedTask.sessionId}),deniedFrame=deniedFrames.frames.find(f=>f.frameId!==0);assert.equal(deniedFrame.allowed,false);await tool('browser_state',{sessionId:deniedTask.sessionId,frameId:deniedFrame.frameId},'frame_not_permitted');checks.push('browser site permission never implies a third-party task grant');
  const navTask=await task('C21'),navState=await observe(navTask),nav=await act(navTask,navState,{type:'click',targetId:target(navState,'Continue','link').id});assert(nav.snapshot.path.startsWith('/destination/'),JSON.stringify(nav));checks.push('same-task navigation obtains a fresh document binding');
  const dialogTask=await task('C23',2),dialogState=await observe(dialogTask),dialogPlan=await tool('browser_plan',{sessionId:dialogTask.sessionId,stateVersion:dialogState.stateVersion,action:{type:'click',targetId:target(dialogState,'Save','button').id,backend:'native'},dialog:{type:'confirm',message:'Save customer?',accept:true}});await tool('browser_commit',{sessionId:dialogTask.sessionId,actionId:dialogPlan.actionId,stateVersion:dialogPlan.stateVersion});await saved(dialogTask);checks.push('exact preauthorized JS confirm handled in owned tab');
  const popupTask=await task('C22',1,{allowPopups:true}),popupState=await observe(popupTask);await act(popupTask,popupState,{type:'click',targetId:target(popupState,'Open customer workspace','button').id});let popup;
  for(let retry=0;retry<30;retry++){popup=(await tool('browser_popups',{sessionId:popupTask.sessionId})).popups[0];if(popup?.status!=='pending'&&popup)break;await new Promise(resolve=>setTimeout(resolve,100));}assert.equal(popup?.status,'ready',JSON.stringify(popup));await tool('browser_session_attach',{sessionId:popupTask.sessionId,tabId:popup.tabId});assert((await observe(popupTask)).snapshot.path.startsWith('/frame/'));checks.push('explicit popup adoption stays within Safe group ownership');
  const handoffTask=await task('C24'),handoffState=await observe(handoffTask);await tool('browser_handoff',{sessionId:handoffTask.sessionId,reason:'mfa'});await tool('browser_plan',{sessionId:handoffTask.sessionId,stateVersion:handoffState.stateVersion,action:{type:'click',targetId:target(handoffState,'Save','button').id}},'needs_user');const resumed=await tool('browser_resume',{sessionId:handoffTask.sessionId});assert.equal(resumed.status,'resumed');checks.push('handoff stops writes and resume discards old refs');
  const site=await tool('browser_site_tools',{sessionId:handoffTask.sessionId});assert.equal(site.status,'unsupported');assert.equal(site.reason,'webmcp_not_enabled');checks.push('disabled experimental integration is explicit');
  const stale=await task('C04',2),before=await observe(stale),old=target(before,'Save','button');const plan=await tool('browser_plan',{sessionId:stale.sessionId,stateVersion:before.stateVersion,action:{type:'click',targetId:old.id}});
  await stale.page.evaluate(()=>{const old=document.querySelector('[role="button"]');old.replaceWith(old.cloneNode(true));});await tool('browser_commit',{sessionId:stale.sessionId,actionId:plan.actionId,stateVersion:before.stateVersion},'stale_reference');checks.push('replacement cannot redirect old planned action');
  const output={passed:true,checks,sensorPairs,kind:'executor_integration',scope:'V2 controls/readers/lifecycle/artifacts integration; development fixtures, not full BCB',seed:11};await mkdir('reports/capabilities',{recursive:true});await writeFile('reports/capabilities/latest.json',JSON.stringify(output,null,2));console.log(JSON.stringify(output));
}finally{
  clearTimeout(watchdog);await client?.close().catch(()=>{});await context?.close().catch(()=>{});readinessServer.closeAllConnections();await new Promise(resolve=>readinessServer.close(resolve));const exited=child.exitCode===null?once(child,'exit'):Promise.resolve();child.kill();await exited;
  assert.equal(path.dirname(directory),base);await rm(directory,{recursive:true,force:true,maxRetries:5,retryDelay:200});
}
